[phases.setup]
providers = ['python']
nixPkgs = ['gcc', 'python38']
aptPkgs = ['libpq-dev','rsyslog-gssapi','libgssapi-krb5-2:i386']

[phases.install]
cmds = ['python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt']

[start]
cmd = '. /opt/venv/bin/activate && gunicorn app:app'